In [ ]:
#India District-wise Agriculture Crop Production (1997–2021)

In [58]:
# STEP 1: LOAD DATA

import pandas as pd

df = pd.read_csv("State_District Level Production Data.csv")

print("Shape:", df.shape)
print("\nColumns:", df.columns)
print("\nSample:")
df.head()

Shape: (246091, 7)

Columns: Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area',
       'Production'],
      dtype='str')

Sample:

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0

In [60]:
# STEP 2: RENAME COLUMNS

df = df.rename(columns={
    "State_Name": "state",
    "District_Name": "district",
    "Crop_Year": "year",
    "Season": "season",
    "Crop": "crop",
    "Area": "area",
    "Production": "production"
})
df

,state,district,year,season,crop,area,production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0
246087,West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0
246088,West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0
246089,West Bengal,PURULIA,2014,Winter,Rice,279151.0,597899.0
246090,West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0

In [61]:
# STEP 3: TEXT CLEANING

text_cols = ["state", "district", "crop", "season"]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

# Remove special characters if any
df["state"] = df["state"].str.replace(r"[^a-z\s]", "", regex=True)
df["district"] = df["district"].str.replace(r"[^a-z\s]", "", regex=True)
df

,state,district,year,season,crop,area,production
0,andaman and nicobar islands,nicobars,2000,kharif,arecanut,1254.0,2000.0
1,andaman and nicobar islands,nicobars,2000,kharif,other kharif pulses,2.0,1.0
2,andaman and nicobar islands,nicobars,2000,kharif,rice,102.0,321.0
3,andaman and nicobar islands,nicobars,2000,whole year,banana,176.0,641.0
4,andaman and nicobar islands,nicobars,2000,whole year,cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,west bengal,purulia,2014,summer,rice,306.0,801.0
246087,west bengal,purulia,2014,summer,sesamum,627.0,463.0
246088,west bengal,purulia,2014,whole year,sugarcane,324.0,16250.0
246089,west bengal,purulia,2014,winter,rice,279151.0,597899.0
246090,west bengal,purulia,2014,winter,sesamum,175.0,88.0

In [62]:
# STEP 4: HANDLE MISSING VALUES

# Drop critical missing values
df = df.dropna(subset=["state", "district", "crop", "year"])

# Fill numerical columns
df["area"] = df["area"].fillna(df["area"].median())
df["production"] = df["production"].fillna(df["production"].median())
df

,state,district,year,season,crop,area,production
0,andaman and nicobar islands,nicobars,2000,kharif,arecanut,1254.0,2000.0
1,andaman and nicobar islands,nicobars,2000,kharif,other kharif pulses,2.0,1.0
2,andaman and nicobar islands,nicobars,2000,kharif,rice,102.0,321.0
3,andaman and nicobar islands,nicobars,2000,whole year,banana,176.0,641.0
4,andaman and nicobar islands,nicobars,2000,whole year,cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,west bengal,purulia,2014,summer,rice,306.0,801.0
246087,west bengal,purulia,2014,summer,sesamum,627.0,463.0
246088,west bengal,purulia,2014,whole year,sugarcane,324.0,16250.0
246089,west bengal,purulia,2014,winter,rice,279151.0,597899.0
246090,west bengal,purulia,2014,winter,sesamum,175.0,88.0

In [64]:
# STEP 5: REMOVE INVALID VALUES

# Remove zero/negative values
df = df[(df["area"] > 0) & (df["production"] > 0)]

# Filter valid year range
df = df[(df["year"] >= 1997) & (df["year"] <= 2021)]

# ROBUST OUTLIER CLIPPING
# AREA
area_low = df["area"].quantile(0.02)
area_high = df["area"].quantile(0.98)

df["area"] = df["area"].clip(area_low, area_high)

# PRODUCTION
prod_low = df["production"].quantile(0.02)
prod_high = df["production"].quantile(0.98)

df["production"] = df["production"].clip(prod_low, prod_high)

df

,state,district,year,season,crop,area,production
0,andaman and nicobar islands,nicobars,2000,kharif,arecanut,1254.0,2000.0000
1,andaman and nicobar islands,nicobars,2000,kharif,other kharif pulses,2.0,1.9000
2,andaman and nicobar islands,nicobars,2000,kharif,rice,102.0,321.0000
3,andaman and nicobar islands,nicobars,2000,whole year,banana,176.0,641.0000
4,andaman and nicobar islands,nicobars,2000,whole year,cashewnut,720.0,165.0000
...,...,...,...,...,...,...,...
246086,west bengal,purulia,2014,summer,rice,306.0,801.0000
246087,west bengal,purulia,2014,summer,sesamum,627.0,463.0000
246088,west bengal,purulia,2014,whole year,sugarcane,324.0,16250.0000
246089,west bengal,purulia,2014,winter,rice,138371.0,477860.7076
246090,west bengal,purulia,2014,winter,sesamum,175.0,88.0000

In [65]:
# STEP 6: REMOVE DUPLICATES

df = df.drop_duplicates().reset_index(drop=True)
df

,state,district,year,season,crop,area,production
0,andaman and nicobar islands,nicobars,2000,kharif,arecanut,1254.0,2000.0000
1,andaman and nicobar islands,nicobars,2000,kharif,other kharif pulses,2.0,1.9000
2,andaman and nicobar islands,nicobars,2000,kharif,rice,102.0,321.0000
3,andaman and nicobar islands,nicobars,2000,whole year,banana,176.0,641.0000
4,andaman and nicobar islands,nicobars,2000,whole year,cashewnut,720.0,165.0000
...,...,...,...,...,...,...,...
242563,west bengal,purulia,2014,summer,rice,306.0,801.0000
242564,west bengal,purulia,2014,summer,sesamum,627.0,463.0000
242565,west bengal,purulia,2014,whole year,sugarcane,324.0,16250.0000
242566,west bengal,purulia,2014,winter,rice,138371.0,477860.7076
242567,west bengal,purulia,2014,winter,sesamum,175.0,88.0000

In [66]:
# EXTRACT UNIQUE CROP NAMES

unique_crops = sorted(df["crop"].dropna().unique())

print("Total Unique Crops:", len(unique_crops))
print("\n--- Crop List ---\n")

for i, crop in enumerate(unique_crops, 1):
    print(f"{i}. {crop}")

Total Unique Crops: 106

--- Crop List ---

1. arcanut (processed)
2. arecanut
3. arhar/tur
4. atcanut (raw)
5. bajra
6. banana
7. barley
8. bean
9. beans & mutter(vegetable)
10. bhindi
11. bitter gourd
12. black pepper
13. blackgram
14. bottle gourd
15. brinjal
16. cabbage
17. cardamom
18. carrot
19. cashewnut
20. cashewnut processed
21. cashewnut raw
22. castor seed
23. cauliflower
24. citrus fruit
25. coconut
26. coffee
27. colocosia
28. cond-spcs other
29. coriander
30. cotton(lint)
31. cowpea(lobia)
32. drum stick
33. dry chillies
34. dry ginger
35. garlic
36. ginger
37. gram
38. grapes
39. groundnut
40. guar seed
41. horse-gram
42. jack fruit
43. jobster
44. jowar
45. jute
46. jute & mesta
47. kapas
48. khesari
49. korra
50. lemon
51. lentil
52. linseed
53. maize
54. mango
55. masoor
56. mesta
57. moong(green gram)
58. moth
59. niger seed
60. oilseeds total
61. onion
62. orange
63. other  rabi pulses
64. other cereals & millets
65. other fresh fruits
66. other kharif pulses
67. other misc. pulses
68. other oilseeds
69. other vegetables
70. paddy
71. papaya
72. peas & beans (pulses)
73. perilla
74. pineapple
75. pome fruit
76. pome granet
77. potato
78. pulses total
79. pump kin
80. ragi
81. rajmash kholar
82. rapeseed &mustard
83. redish
84. rice
85. ricebean (nagadal)
86. rubber
87. safflower
88. samai
89. sannhamp
90. sapota
91. sesamum
92. small millets
93. soyabean
94. sugarcane
95. sunflower
96. sweet potato
97. tapioca
98. tea
99. tobacco
100. tomato
101. total foodgrain
102. turmeric
103. turnip
104. urad
105. varagu
106. wheat

In [67]:
#STEP 7: NORMALISATION
#Crop normalization

crop_map = {

    # 70, 84 → Rice
    "paddy": "rice",                 # 70
    "rice": "rice",                  # 84

    # 30, 47 → Cotton
    "cotton(lint)": "cotton",        # 30
    "kapas": "cotton",               # 47

    # Pulses
    "moong(green gram)": "moong",    # 57
    "blackgram": "urad",             # 13
    "urad": "urad",                  # 104
    "arhar/tur": "tur",            # 3
    "gram": "gram",                  # 37
    "lentil": "lentil",              # 51
    "masoor": "masoor",              # 55
    "peas & beans (pulses)": "pulses", # 72
    "cowpea(lobia)": "cowpea",       # 31

    # Oilseeds
    "groundnut": "groundnut",        # 39
    "sesamum": "sesamum",            # 91
    "soyabean": "soybean",           # 93
    "sunflower": "sunflower",        # 95
    "rapeseed &mustard": "rapeseed_mustard", # 82
    "niger seed": "niger",           # 59
    "castor seed": "castor",         # 22
    "linseed": "linseed",            # 52

    # Cereals & Millets
    "bajra": "bajra",                # 5
    "jowar": "jowar",                # 44
    "ragi": "ragi",                  # 80
    "maize": "maize",                # 53
    "wheat": "wheat",                # 106
    "barley": "barley",              # 7
    "small millets": "millets",      # 92
    "samai": "millets",              # 88
    "varagu": "millets",             # 105
    "korra": "millets",              # 49

    # Plantation / Commercial
    "sugarcane": "sugarcane",        # 94
    "coffee": "coffee",              # 26
    "tea": "tea",                    # 98
    "tobacco": "tobacco",            # 99
    "rubber": "rubber",              # 86

    # Spices
    "dry chillies": "chillies",      # 33
    "turmeric": "turmeric",          # 102
    "ginger": "ginger",              # 36
    "dry ginger": "ginger",          # 34
    "black pepper": "pepper",        # 12
    "cardamom": "cardamom",          # 17
    "coriander": "coriander",        # 29

    # Fruits
    "banana": "banana",              # 6
    "mango": "mango",                # 54
    "grapes": "grapes",              # 38
    "orange": "orange",              # 62
    "lemon": "lemon",                # 50
    "papaya": "papaya",              # 71
    "pineapple": "pineapple",        # 74
    "sapota": "sapota",              # 90
    "pome granet": "pomegranate",    # 76

    # Vegetables
    "onion": "onion",                # 61
    "potato": "potato",              # 77
    "tomato": "tomato",              # 100
    "cabbage": "cabbage",            # 15
    "cauliflower": "cauliflower",    # 23
    "brinjal": "brinjal",            # 14
    "bhindi": "okra",                # 10
    "pump kin": "pumpkin",           # 79
    "bottle gourd": "bottle gourd",         # 14 (approx group)
    "bitter gourd": "bitter gourd",         # 11

    # Nuts / Plantation
    "arecanut": "arecanut",          # 2
    "arcanut (processed)": "arecanut", # 1
    "atcanut (raw)": "arecanut",     # 4
    "cashewnut": "cashew",           # 19
    "cashewnut raw": "cashew",       # 21
    "cashewnut processed": "cashew", # 20
    "coconut": "coconut",            # 25

    # Others (useful)
    "jute": "jute",                  # 45
    "jute & mesta": "jute",          # 46
    "mesta": "mesta",                # 56
    "safflower": "safflower",        # 87
    "guar seed": "guar",             # 40
    "horse-gram": "horsegram",       # 41

    # ❌ REMOVE (aggregate / noisy categories)
    "total foodgrain": None,         # 101
    "oilseeds total": None,          # 60
    "pulses total": None,            # 78
    "other oilseeds": None,          # 68
    "other vegetables": None,        # 69
    "other fresh fruits": None,      # 65
    "other cereals & millets": None, # 64
    "other kharif pulses": None,     # 66
    "other rabi pulses": None,       # 63
    "other misc. pulses": None,      # 67
    "cond-spcs other": None          # 28
}
df["crop"] = df["crop"].replace(crop_map)

#Season Normalization
season_map = {
    "kharif": "kharif",
    "rabi": "rabi",
    "summer": "summer",
    "whole year": "annual",
    "winter": "rabi",
    "autumn": "kharif"
}

df["season"] = df["season"].map(season_map)

# Drop unwanted categories
df = df[df["crop"].notna()]
df = df[df["season"].notna()]
df

,state,district,year,season,crop,area,production
0,andaman and nicobar islands,nicobars,2000,kharif,arecanut,1254.0,2000.0000
2,andaman and nicobar islands,nicobars,2000,kharif,rice,102.0,321.0000
3,andaman and nicobar islands,nicobars,2000,annual,banana,176.0,641.0000
4,andaman and nicobar islands,nicobars,2000,annual,cashew,720.0,165.0000
5,andaman and nicobar islands,nicobars,2000,annual,coconut,18168.0,477860.7076
...,...,...,...,...,...,...,...
242563,west bengal,purulia,2014,summer,rice,306.0,801.0000
242564,west bengal,purulia,2014,summer,sesamum,627.0,463.0000
242565,west bengal,purulia,2014,annual,sugarcane,324.0,16250.0000
242566,west bengal,purulia,2014,rabi,rice,138371.0,477860.7076
242567,west bengal,purulia,2014,rabi,sesamum,175.0,88.0000

In [69]:
# STEP 8: FEATURE ENGINEERING
import numpy as np
# Yield calculation
df["yield"] = df["production"] / df["area"]
lower = df["yield"].quantile(0.01)
upper = df["yield"].quantile(0.99)

df["yield"] = df["yield"].clip(lower, upper)

df["yield_log"] = np.log1p(df["yield"])

# CREATE RISK LABEL
low = df["yield_log"].quantile(0.33)
high = df["yield_log"].quantile(0.66)

def risk_label(y):
    if y < low:
        return 2   # High Risk
    elif y < high:
        return 1   # Medium Risk
    else:
        return 0   # Low Risk

df["risk"] = df["yield_log"].apply(risk_label)
df

,state,district,year,season,crop,area,production,yield,yield_log,risk
0,andaman and nicobar islands,nicobars,2000,kharif,arecanut,1254.0,2000.0000,1.594896,0.953547,1
2,andaman and nicobar islands,nicobars,2000,kharif,rice,102.0,321.0000,3.147059,1.422399,0
3,andaman and nicobar islands,nicobars,2000,annual,banana,176.0,641.0000,3.642045,1.535155,0
4,andaman and nicobar islands,nicobars,2000,annual,cashew,720.0,165.0000,0.229167,0.206336,2
5,andaman and nicobar islands,nicobars,2000,annual,coconut,18168.0,477860.7076,26.302329,3.306972,0
...,...,...,...,...,...,...,...,...,...,...
242563,west bengal,purulia,2014,summer,rice,306.0,801.0000,2.617647,1.285824,0
242564,west bengal,purulia,2014,summer,sesamum,627.0,463.0000,0.738437,0.552986,1
242565,west bengal,purulia,2014,annual,sugarcane,324.0,16250.0000,50.154321,3.934847,0
242566,west bengal,purulia,2014,rabi,rice,138371.0,477860.7076,3.453474,1.493685,0
242567,west bengal,purulia,2014,rabi,sesamum,175.0,88.0000,0.502857,0.407368,2

In [70]:
# STEP 9: VALIDATION

print("Final Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nUnique Seasons:", df["season"].unique())

print("\nTop Crops:")
print(df["crop"].value_counts().head())

print("\nSummary:")
df.describe()

Final Shape: (236496, 10)

Missing Values:
state         0
district      0
year          0
season        0
crop          0
area          0
production    0
yield         0
yield_log     0
risk          0
dtype: int64

Unique Seasons: <StringArray>
['kharif', 'annual', 'rabi', 'summer']
Length: 4, dtype: str

Top Crops:
crop
rice       15579
maize      13883
moong      10249
urad        9927
sesamum     8949
Name: count, dtype: int64

Summary:

,year,area,production,yield,yield_log,risk
count,236496.000000,236496.000000,236496.000000,236496.000000,236496.000000,236496.000000
mean,2005.710579,10322.926494,28098.117754,5.535383,1.070435,0.989987
std,4.967255,26672.222951,85824.884934,15.977759,0.964394,0.818475
min,1997.000000,2.000000,1.900000,0.104471,0.099367,0.000000
25%,2002.000000,84.000000,100.000000,0.566667,0.448950,0.000000
50%,2006.000000,600.000000,754.000000,1.028571,0.707332,1.000000
75%,2010.000000,4612.250000,7314.250000,2.629042,1.288969,2.000000
max,2015.000000,138371.000000,477860.707600,121.500000,4.808111,2.000000

In [75]:
# STEP 10: CURATED DATASET
import pandas as pd
final_df = df[[
    "state",
    "district",
    "year",
    "season",
    "crop",
    "area",
    "production",
    "yield_log",
    "risk"
]].reset_index(drop=True)

final_df.to_csv("Dataset_X.csv", index=False)

print("Final curated dataset saved")

df=pd.read_csv("Dataset_X.csv")
df

Final curated dataset saved

,state,district,year,season,crop,area,production,yield_log,risk
0,andaman and nicobar islands,nicobars,2000,kharif,arecanut,1254.0,2000.0000,0.953547,1
1,andaman and nicobar islands,nicobars,2000,kharif,rice,102.0,321.0000,1.422399,0
2,andaman and nicobar islands,nicobars,2000,annual,banana,176.0,641.0000,1.535155,0
3,andaman and nicobar islands,nicobars,2000,annual,cashew,720.0,165.0000,0.206336,2
4,andaman and nicobar islands,nicobars,2000,annual,coconut,18168.0,477860.7076,3.306972,0
...,...,...,...,...,...,...,...,...,...
236491,west bengal,purulia,2014,summer,rice,306.0,801.0000,1.285824,0
236492,west bengal,purulia,2014,summer,sesamum,627.0,463.0000,0.552986,1
236493,west bengal,purulia,2014,annual,sugarcane,324.0,16250.0000,3.934847,0
236494,west bengal,purulia,2014,rabi,rice,138371.0,477860.7076,1.493685,0
236495,west bengal,purulia,2014,rabi,sesamum,175.0,88.0000,0.407368,2