In [87]:
# LOAD SOIL DATASET

import pandas as pd

df = pd.read_csv("CropDataset-Enhanced.csv")

print("Shape:", df_soil.shape)
print("\nColumns:", df_soil.columns)
df_soil.head()

Shape: (730, 23)

Columns: Index(['address', 'status geocode', 'district', 'latitude', 'longitude',
       'type', 'location type', 'country', 'state', 'crop_raw',
       'nitrogen - high', 'nitrogen - medium', 'nitrogen - low',
       'phosphorous - high', 'phosphorous - medium', 'phosphorous - low',
       'potassium - high', 'potassium - medium', 'potassium - low',
       'ph - acidic', 'ph - neutral', 'ph - alkaline', 'crop'],
      dtype='str')

,address,status geocode,district,latitude,longitude,type,location type,country,state,crop_raw,...,phosphorous - high,phosphorous - medium,phosphorous - low,potassium - high,potassium - medium,potassium - low,ph - acidic,ph - neutral,ph - alkaline,crop
0,Ahilya nagar,Ok,"ahilya nagar, maharashtra, india",19.094829,74.747979,"locality, political",APPROXIMATE,India,maharashtra,"Sugarcane, Bajra (Pearl Millet), Wheat, Cotton...",...,74.02%,21.09%,4.89%,39.15%,42.81%,18.04%,0.11%,96.02%,3.87%,sugarcane
1,Akola,Ok,"akola, maharashtra, india",20.700216,77.008168,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,68.52%,28.76%,2.72%,84.11%,14.74%,1.14%,0%,95.62%,4.38%,cotton
2,Amravati,Ok,"amravati, maharashtra, india",20.931982,77.752304,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,9.76%,28.19%,62.05%,80.88%,6.25%,12.87%,13.44%,84.55%,2.01%,cotton
3,"Chhatrapati Sambhaji Nagar, Maharashtra",Ok,"chhatrapati sambhaji nagar, maharashtra, india",19.875754,75.339320,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,61.51%,30.92%,7.57%,73.23%,24.86%,1.91%,0%,90.48%,9.52%,cotton
4,"Beed, Maharashtra",Ok,"beed, maharashtra 431122, india",18.990088,75.753132,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,13.78%,75.24%,10.98%,52.74%,42.98%,4.28%,0.11%,90.24%,9.65%,cotton

In [88]:
# Drop empty column
df = df.drop(columns=[" "], errors="ignore")

# Standardize column names
df.columns = df.columns.str.lower().str.strip()
df

,address,status geocode,formatted address,latitude,longitude,type,location type,country,region,crop,...,nitrogen - low,phosphorous - high,phosphorous - medium,phosphorous - low,potassium - high,potassium - medium,potassium - low,ph - acidic,ph - neutral,ph - alkaline
0,Ahilya nagar,Ok,"Ahilya Nagar, Maharashtra, India",19.094829,74.747979,"locality, political",APPROXIMATE,India,Maharashtra,"Sugarcane, Bajra (Pearl Millet), Wheat, Cotton...",...,96.42%,74.02%,21.09%,4.89%,39.15%,42.81%,18.04%,0.11%,96.02%,3.87%
1,Akola,Ok,"Akola, Maharashtra, India",20.700216,77.008168,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,99.67%,68.52%,28.76%,2.72%,84.11%,14.74%,1.14%,0%,95.62%,4.38%
2,Amravati,Ok,"Amravati, Maharashtra, India",20.931982,77.752304,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,99.03%,9.76%,28.19%,62.05%,80.88%,6.25%,12.87%,13.44%,84.55%,2.01%
3,"Chhatrapati Sambhaji Nagar, Maharashtra",Ok,"Chhatrapati Sambhaji Nagar, Maharashtra, India",19.875754,75.339320,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,98.07%,61.51%,30.92%,7.57%,73.23%,24.86%,1.91%,0%,90.48%,9.52%
4,"Beed, Maharashtra",Ok,"Beed, Maharashtra 431122, India",18.990088,75.753132,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,61.25%,13.78%,75.24%,10.98%,52.74%,42.98%,4.28%,0.11%,90.24%,9.65%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,"Leh, Ladakh",Ok,Leh,34.152586,77.577054,"locality, political",APPROXIMATE,India,Ladakh,"Barley, Buckwheat, Mustard, Peas",...,0%,36.64%,32.82%,30.53%,61.83%,22.90%,15.27%,0%,95.42%,4.58%
726,Lakshadweep,Ok,"Lakshadweep, India",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,Lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,"Lakshadweep, Lakshadweep",Ok,"Lakshadweep, India",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,Lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,"Karaikal, Puducherry",Ok,"Karaikal, Puducherry, India",10.925440,79.838006,"locality, political",APPROXIMATE,India,Puducherry,"Paddy, Sugarcane, Pulses, Coconut",...,100%,53.40%,42.40%,4.20%,29.20%,50.40%,20.40%,3.30%,95.60%,1.10%
729,"Puducherry, Puducherry",Ok,"Puducherry, India",11.941591,79.808313,"locality, political",APPROXIMATE,India,Puducherry,"Paddy, Sugarcane, Groundnut, Vegetables",...,100%,72.41%,22.53%,5.06%,28.04%,43.00%,28.95%,1.76%,92.66%,5.58%

In [89]:
df = df.rename(columns={
    "region": "state",
    "formatted address": "district",
    "crop": "crop_raw"
})
df

,address,status geocode,district,latitude,longitude,type,location type,country,state,crop_raw,...,nitrogen - low,phosphorous - high,phosphorous - medium,phosphorous - low,potassium - high,potassium - medium,potassium - low,ph - acidic,ph - neutral,ph - alkaline
0,Ahilya nagar,Ok,"Ahilya Nagar, Maharashtra, India",19.094829,74.747979,"locality, political",APPROXIMATE,India,Maharashtra,"Sugarcane, Bajra (Pearl Millet), Wheat, Cotton...",...,96.42%,74.02%,21.09%,4.89%,39.15%,42.81%,18.04%,0.11%,96.02%,3.87%
1,Akola,Ok,"Akola, Maharashtra, India",20.700216,77.008168,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,99.67%,68.52%,28.76%,2.72%,84.11%,14.74%,1.14%,0%,95.62%,4.38%
2,Amravati,Ok,"Amravati, Maharashtra, India",20.931982,77.752304,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,99.03%,9.76%,28.19%,62.05%,80.88%,6.25%,12.87%,13.44%,84.55%,2.01%
3,"Chhatrapati Sambhaji Nagar, Maharashtra",Ok,"Chhatrapati Sambhaji Nagar, Maharashtra, India",19.875754,75.339320,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,98.07%,61.51%,30.92%,7.57%,73.23%,24.86%,1.91%,0%,90.48%,9.52%
4,"Beed, Maharashtra",Ok,"Beed, Maharashtra 431122, India",18.990088,75.753132,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,61.25%,13.78%,75.24%,10.98%,52.74%,42.98%,4.28%,0.11%,90.24%,9.65%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,"Leh, Ladakh",Ok,Leh,34.152586,77.577054,"locality, political",APPROXIMATE,India,Ladakh,"Barley, Buckwheat, Mustard, Peas",...,0%,36.64%,32.82%,30.53%,61.83%,22.90%,15.27%,0%,95.42%,4.58%
726,Lakshadweep,Ok,"Lakshadweep, India",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,Lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,"Lakshadweep, Lakshadweep",Ok,"Lakshadweep, India",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,Lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,"Karaikal, Puducherry",Ok,"Karaikal, Puducherry, India",10.925440,79.838006,"locality, political",APPROXIMATE,India,Puducherry,"Paddy, Sugarcane, Pulses, Coconut",...,100%,53.40%,42.40%,4.20%,29.20%,50.40%,20.40%,3.30%,95.60%,1.10%
729,"Puducherry, Puducherry",Ok,"Puducherry, India",11.941591,79.808313,"locality, political",APPROXIMATE,India,Puducherry,"Paddy, Sugarcane, Groundnut, Vegetables",...,100%,72.41%,22.53%,5.06%,28.04%,43.00%,28.95%,1.76%,92.66%,5.58%

In [90]:
import numpy as np

def percent_to_float(x):
    if isinstance(x, str):
        return float(x.replace("%", "").strip())
    return np.nan

for col in df.columns:
    if "%" in str(df[col].iloc[0]):
        df[col] = df[col].apply(percent_to_float)

df

,address,status geocode,district,latitude,longitude,type,location type,country,state,crop_raw,...,nitrogen - low,phosphorous - high,phosphorous - medium,phosphorous - low,potassium - high,potassium - medium,potassium - low,ph - acidic,ph - neutral,ph - alkaline
0,Ahilya nagar,Ok,"Ahilya Nagar, Maharashtra, India",19.094829,74.747979,"locality, political",APPROXIMATE,India,Maharashtra,"Sugarcane, Bajra (Pearl Millet), Wheat, Cotton...",...,96.42,74.02,21.09,4.89,39.15,42.81,18.04,0.11,96.02,3.87
1,Akola,Ok,"Akola, Maharashtra, India",20.700216,77.008168,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,99.67,68.52,28.76,2.72,84.11,14.74,1.14,0.00,95.62,4.38
2,Amravati,Ok,"Amravati, Maharashtra, India",20.931982,77.752304,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,99.03,9.76,28.19,62.05,80.88,6.25,12.87,13.44,84.55,2.01
3,"Chhatrapati Sambhaji Nagar, Maharashtra",Ok,"Chhatrapati Sambhaji Nagar, Maharashtra, India",19.875754,75.339320,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,98.07,61.51,30.92,7.57,73.23,24.86,1.91,0.00,90.48,9.52
4,"Beed, Maharashtra",Ok,"Beed, Maharashtra 431122, India",18.990088,75.753132,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,61.25,13.78,75.24,10.98,52.74,42.98,4.28,0.11,90.24,9.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,"Leh, Ladakh",Ok,Leh,34.152586,77.577054,"locality, political",APPROXIMATE,India,Ladakh,"Barley, Buckwheat, Mustard, Peas",...,0.00,36.64,32.82,30.53,61.83,22.90,15.27,0.00,95.42,4.58
726,Lakshadweep,Ok,"Lakshadweep, India",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,Lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,"Lakshadweep, Lakshadweep",Ok,"Lakshadweep, India",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,Lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,"Karaikal, Puducherry",Ok,"Karaikal, Puducherry, India",10.925440,79.838006,"locality, political",APPROXIMATE,India,Puducherry,"Paddy, Sugarcane, Pulses, Coconut",...,100.00,53.40,42.40,4.20,29.20,50.40,20.40,3.30,95.60,1.10
729,"Puducherry, Puducherry",Ok,"Puducherry, India",11.941591,79.808313,"locality, political",APPROXIMATE,India,Puducherry,"Paddy, Sugarcane, Groundnut, Vegetables",...,100.00,72.41,22.53,5.06,28.04,43.00,28.95,1.76,92.66,5.58

In [91]:
df["n"] = (
    df["nitrogen - high"] * 3 +
    df["nitrogen - medium"] * 2 +
    df["nitrogen - low"] * 1
) / 100

df["p"] = (
    df["phosphorous - high"] * 3 +
    df["phosphorous - medium"] * 2 +
    df["phosphorous - low"] * 1
) / 100

df["k"] = (
    df["potassium - high"] * 3 +
    df["potassium - medium"] * 2 +
    df["potassium - low"] * 1
) / 100

df["ph"] = (
    df["ph - acidic"] * 5 +
    df["ph - neutral"] * 7 +
    df["ph - alkaline"] * 9
) / 100

df

,address,status geocode,district,latitude,longitude,type,location type,country,state,crop_raw,...,potassium - high,potassium - medium,potassium - low,ph - acidic,ph - neutral,ph - alkaline,n,p,k,ph
0,Ahilya nagar,Ok,"Ahilya Nagar, Maharashtra, India",19.094829,74.747979,"locality, political",APPROXIMATE,India,Maharashtra,"Sugarcane, Bajra (Pearl Millet), Wheat, Cotton...",...,39.15,42.81,18.04,0.11,96.02,3.87,1.0361,2.6913,2.2111,7.0752
1,Akola,Ok,"Akola, Maharashtra, India",20.700216,77.008168,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,84.11,14.74,1.14,0.00,95.62,4.38,1.0038,2.6580,2.8295,7.0876
2,Amravati,Ok,"Amravati, Maharashtra, India",20.931982,77.752304,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,80.88,6.25,12.87,13.44,84.55,2.01,1.0107,1.4771,2.6801,6.7714
3,"Chhatrapati Sambhaji Nagar, Maharashtra",Ok,"Chhatrapati Sambhaji Nagar, Maharashtra, India",19.875754,75.339320,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,73.23,24.86,1.91,0.00,90.48,9.52,1.0198,2.5394,2.7132,7.1904
4,"Beed, Maharashtra",Ok,"Beed, Maharashtra 431122, India",18.990088,75.753132,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,52.74,42.98,4.28,0.11,90.24,9.65,1.4096,2.0280,2.4846,7.1908
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,"Leh, Ladakh",Ok,Leh,34.152586,77.577054,"locality, political",APPROXIMATE,India,Ladakh,"Barley, Buckwheat, Mustard, Peas",...,61.83,22.90,15.27,0.00,95.42,4.58,0.0000,2.0609,2.4656,7.0916
726,Lakshadweep,Ok,"Lakshadweep, India",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,Lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,"Lakshadweep, Lakshadweep",Ok,"Lakshadweep, India",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,Lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,"Karaikal, Puducherry",Ok,"Karaikal, Puducherry, India",10.925440,79.838006,"locality, political",APPROXIMATE,India,Puducherry,"Paddy, Sugarcane, Pulses, Coconut",...,29.20,50.40,20.40,3.30,95.60,1.10,1.0000,2.4920,2.0880,6.9560
729,"Puducherry, Puducherry",Ok,"Puducherry, India",11.941591,79.808313,"locality, political",APPROXIMATE,India,Puducherry,"Paddy, Sugarcane, Groundnut, Vegetables",...,28.04,43.00,28.95,1.76,92.66,5.58,1.0000,2.6735,1.9907,7.0764

In [92]:
df["crop"] = df["crop_raw"].str.split(",").str[0].str.lower().str.strip()
df

,address,status geocode,district,latitude,longitude,type,location type,country,state,crop_raw,...,potassium - medium,potassium - low,ph - acidic,ph - neutral,ph - alkaline,n,p,k,ph,crop
0,Ahilya nagar,Ok,"Ahilya Nagar, Maharashtra, India",19.094829,74.747979,"locality, political",APPROXIMATE,India,Maharashtra,"Sugarcane, Bajra (Pearl Millet), Wheat, Cotton...",...,42.81,18.04,0.11,96.02,3.87,1.0361,2.6913,2.2111,7.0752,sugarcane
1,Akola,Ok,"Akola, Maharashtra, India",20.700216,77.008168,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,14.74,1.14,0.00,95.62,4.38,1.0038,2.6580,2.8295,7.0876,cotton
2,Amravati,Ok,"Amravati, Maharashtra, India",20.931982,77.752304,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,6.25,12.87,13.44,84.55,2.01,1.0107,1.4771,2.6801,6.7714,cotton
3,"Chhatrapati Sambhaji Nagar, Maharashtra",Ok,"Chhatrapati Sambhaji Nagar, Maharashtra, India",19.875754,75.339320,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,24.86,1.91,0.00,90.48,9.52,1.0198,2.5394,2.7132,7.1904,cotton
4,"Beed, Maharashtra",Ok,"Beed, Maharashtra 431122, India",18.990088,75.753132,"locality, political",APPROXIMATE,India,Maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,42.98,4.28,0.11,90.24,9.65,1.4096,2.0280,2.4846,7.1908,cotton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,"Leh, Ladakh",Ok,Leh,34.152586,77.577054,"locality, political",APPROXIMATE,India,Ladakh,"Barley, Buckwheat, Mustard, Peas",...,22.90,15.27,0.00,95.42,4.58,0.0000,2.0609,2.4656,7.0916,barley
726,Lakshadweep,Ok,"Lakshadweep, India",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,Lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coconut
727,"Lakshadweep, Lakshadweep",Ok,"Lakshadweep, India",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,Lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coconut
728,"Karaikal, Puducherry",Ok,"Karaikal, Puducherry, India",10.925440,79.838006,"locality, political",APPROXIMATE,India,Puducherry,"Paddy, Sugarcane, Pulses, Coconut",...,50.40,20.40,3.30,95.60,1.10,1.0000,2.4920,2.0880,6.9560,paddy
729,"Puducherry, Puducherry",Ok,"Puducherry, India",11.941591,79.808313,"locality, political",APPROXIMATE,India,Puducherry,"Paddy, Sugarcane, Groundnut, Vegetables",...,43.00,28.95,1.76,92.66,5.58,1.0000,2.6735,1.9907,7.0764,paddy

In [93]:
for col in ["state", "district", "crop"]:
    df[col] = df[col].astype(str).str.lower().str.strip()
df

,address,status geocode,district,latitude,longitude,type,location type,country,state,crop_raw,...,potassium - medium,potassium - low,ph - acidic,ph - neutral,ph - alkaline,n,p,k,ph,crop
0,Ahilya nagar,Ok,"ahilya nagar, maharashtra, india",19.094829,74.747979,"locality, political",APPROXIMATE,India,maharashtra,"Sugarcane, Bajra (Pearl Millet), Wheat, Cotton...",...,42.81,18.04,0.11,96.02,3.87,1.0361,2.6913,2.2111,7.0752,sugarcane
1,Akola,Ok,"akola, maharashtra, india",20.700216,77.008168,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,14.74,1.14,0.00,95.62,4.38,1.0038,2.6580,2.8295,7.0876,cotton
2,Amravati,Ok,"amravati, maharashtra, india",20.931982,77.752304,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,6.25,12.87,13.44,84.55,2.01,1.0107,1.4771,2.6801,6.7714,cotton
3,"Chhatrapati Sambhaji Nagar, Maharashtra",Ok,"chhatrapati sambhaji nagar, maharashtra, india",19.875754,75.339320,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,24.86,1.91,0.00,90.48,9.52,1.0198,2.5394,2.7132,7.1904,cotton
4,"Beed, Maharashtra",Ok,"beed, maharashtra 431122, india",18.990088,75.753132,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,42.98,4.28,0.11,90.24,9.65,1.4096,2.0280,2.4846,7.1908,cotton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,"Leh, Ladakh",Ok,leh,34.152586,77.577054,"locality, political",APPROXIMATE,India,ladakh,"Barley, Buckwheat, Mustard, Peas",...,22.90,15.27,0.00,95.42,4.58,0.0000,2.0609,2.4656,7.0916,barley
726,Lakshadweep,Ok,"lakshadweep, india",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coconut
727,"Lakshadweep, Lakshadweep",Ok,"lakshadweep, india",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coconut
728,"Karaikal, Puducherry",Ok,"karaikal, puducherry, india",10.925440,79.838006,"locality, political",APPROXIMATE,India,puducherry,"Paddy, Sugarcane, Pulses, Coconut",...,50.40,20.40,3.30,95.60,1.10,1.0000,2.4920,2.0880,6.9560,paddy
729,"Puducherry, Puducherry",Ok,"puducherry, india",11.941591,79.808313,"locality, political",APPROXIMATE,India,puducherry,"Paddy, Sugarcane, Groundnut, Vegetables",...,43.00,28.95,1.76,92.66,5.58,1.0000,2.6735,1.9907,7.0764,paddy

In [94]:
for col in ["state", "district", "crop"]:
    df[col] = df[col].astype(str).str.lower().str.strip()
df

,address,status geocode,district,latitude,longitude,type,location type,country,state,crop_raw,...,potassium - medium,potassium - low,ph - acidic,ph - neutral,ph - alkaline,n,p,k,ph,crop
0,Ahilya nagar,Ok,"ahilya nagar, maharashtra, india",19.094829,74.747979,"locality, political",APPROXIMATE,India,maharashtra,"Sugarcane, Bajra (Pearl Millet), Wheat, Cotton...",...,42.81,18.04,0.11,96.02,3.87,1.0361,2.6913,2.2111,7.0752,sugarcane
1,Akola,Ok,"akola, maharashtra, india",20.700216,77.008168,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,14.74,1.14,0.00,95.62,4.38,1.0038,2.6580,2.8295,7.0876,cotton
2,Amravati,Ok,"amravati, maharashtra, india",20.931982,77.752304,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,6.25,12.87,13.44,84.55,2.01,1.0107,1.4771,2.6801,6.7714,cotton
3,"Chhatrapati Sambhaji Nagar, Maharashtra",Ok,"chhatrapati sambhaji nagar, maharashtra, india",19.875754,75.339320,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,24.86,1.91,0.00,90.48,9.52,1.0198,2.5394,2.7132,7.1904,cotton
4,"Beed, Maharashtra",Ok,"beed, maharashtra 431122, india",18.990088,75.753132,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,42.98,4.28,0.11,90.24,9.65,1.4096,2.0280,2.4846,7.1908,cotton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,"Leh, Ladakh",Ok,leh,34.152586,77.577054,"locality, political",APPROXIMATE,India,ladakh,"Barley, Buckwheat, Mustard, Peas",...,22.90,15.27,0.00,95.42,4.58,0.0000,2.0609,2.4656,7.0916,barley
726,Lakshadweep,Ok,"lakshadweep, india",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coconut
727,"Lakshadweep, Lakshadweep",Ok,"lakshadweep, india",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coconut
728,"Karaikal, Puducherry",Ok,"karaikal, puducherry, india",10.925440,79.838006,"locality, political",APPROXIMATE,India,puducherry,"Paddy, Sugarcane, Pulses, Coconut",...,50.40,20.40,3.30,95.60,1.10,1.0000,2.4920,2.0880,6.9560,paddy
729,"Puducherry, Puducherry",Ok,"puducherry, india",11.941591,79.808313,"locality, political",APPROXIMATE,India,puducherry,"Paddy, Sugarcane, Groundnut, Vegetables",...,43.00,28.95,1.76,92.66,5.58,1.0000,2.6735,1.9907,7.0764,paddy

In [95]:
df["soil_fertility"] = (df["n"] + df["p"] + df["k"]) / 3
df

,address,status geocode,district,latitude,longitude,type,location type,country,state,crop_raw,...,potassium - low,ph - acidic,ph - neutral,ph - alkaline,n,p,k,ph,crop,soil_fertility
0,Ahilya nagar,Ok,"ahilya nagar, maharashtra, india",19.094829,74.747979,"locality, political",APPROXIMATE,India,maharashtra,"Sugarcane, Bajra (Pearl Millet), Wheat, Cotton...",...,18.04,0.11,96.02,3.87,1.0361,2.6913,2.2111,7.0752,sugarcane,1.979500
1,Akola,Ok,"akola, maharashtra, india",20.700216,77.008168,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,1.14,0.00,95.62,4.38,1.0038,2.6580,2.8295,7.0876,cotton,2.163767
2,Amravati,Ok,"amravati, maharashtra, india",20.931982,77.752304,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Soybean, Jowar (Sorghum), Wheat, Tur (...",...,12.87,13.44,84.55,2.01,1.0107,1.4771,2.6801,6.7714,cotton,1.722633
3,"Chhatrapati Sambhaji Nagar, Maharashtra",Ok,"chhatrapati sambhaji nagar, maharashtra, india",19.875754,75.339320,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,1.91,0.00,90.48,9.52,1.0198,2.5394,2.7132,7.1904,cotton,2.090800
4,"Beed, Maharashtra",Ok,"beed, maharashtra 431122, india",18.990088,75.753132,"locality, political",APPROXIMATE,India,maharashtra,"Cotton, Bajra (Pearl Millet), Wheat, Sugarcane...",...,4.28,0.11,90.24,9.65,1.4096,2.0280,2.4846,7.1908,cotton,1.974067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,"Leh, Ladakh",Ok,leh,34.152586,77.577054,"locality, political",APPROXIMATE,India,ladakh,"Barley, Buckwheat, Mustard, Peas",...,15.27,0.00,95.42,4.58,0.0000,2.0609,2.4656,7.0916,barley,1.508833
726,Lakshadweep,Ok,"lakshadweep, india",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coconut,NaN
727,"Lakshadweep, Lakshadweep",Ok,"lakshadweep, india",9.985089,72.932473,"administrative_area_level_1, political",APPROXIMATE,India,lakshadweep,"Coconut, Banana, Breadfruit, Tuber crops",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coconut,NaN
728,"Karaikal, Puducherry",Ok,"karaikal, puducherry, india",10.925440,79.838006,"locality, political",APPROXIMATE,India,puducherry,"Paddy, Sugarcane, Pulses, Coconut",...,20.40,3.30,95.60,1.10,1.0000,2.4920,2.0880,6.9560,paddy,1.860000
729,"Puducherry, Puducherry",Ok,"puducherry, india",11.941591,79.808313,"locality, political",APPROXIMATE,India,puducherry,"Paddy, Sugarcane, Groundnut, Vegetables",...,28.95,1.76,92.66,5.58,1.0000,2.6735,1.9907,7.0764,paddy,1.888067

In [96]:
df = df[[
    "state",
    "district",
    "crop",
    "latitude",
    "longitude",
    "n",
    "p",
    "k",
    "ph",
    "soil_fertility"
]]
df=df.dropna(subset=["n", "p", "k", "ph", "soil_fertility"])
df

,state,district,crop,latitude,longitude,n,p,k,ph,soil_fertility
0,maharashtra,"ahilya nagar, maharashtra, india",sugarcane,19.094829,74.747979,1.0361,2.6913,2.2111,7.0752,1.979500
1,maharashtra,"akola, maharashtra, india",cotton,20.700216,77.008168,1.0038,2.6580,2.8295,7.0876,2.163767
2,maharashtra,"amravati, maharashtra, india",cotton,20.931982,77.752304,1.0107,1.4771,2.6801,6.7714,1.722633
3,maharashtra,"chhatrapati sambhaji nagar, maharashtra, india",cotton,19.875754,75.339320,1.0198,2.5394,2.7132,7.1904,2.090800
4,maharashtra,"beed, maharashtra 431122, india",cotton,18.990088,75.753132,1.4096,2.0280,2.4846,7.1908,1.974067
...,...,...,...,...,...,...,...,...,...,...
723,jammu and kashmir,udhampur 182101,maize,32.915985,75.141617,2.2599,2.0020,1.8207,7.0000,2.027533
724,ladakh,kargil 194103,barley,34.553852,76.134894,0.0000,1.7143,1.8572,7.2858,1.190500
725,ladakh,leh,barley,34.152586,77.577054,0.0000,2.0609,2.4656,7.0916,1.508833
728,puducherry,"karaikal, puducherry, india",paddy,10.925440,79.838006,1.0000,2.4920,2.0880,6.9560,1.860000
729,puducherry,"puducherry, india",paddy,11.941591,79.808313,1.0000,2.6735,1.9907,7.0764,1.888067

In [97]:
print("\nMissing values:")
print(df.isnull().sum())

print("\nShape:", df.shape)
df.describe()

Missing values:
state             0
district          0
crop              0
latitude          0
longitude         0
n                 0
p                 0
k                 0
ph                0
soil_fertility    0
dtype: int64

Shape: (695, 10)

,latitude,longitude,n,p,k,ph,soil_fertility
count,695.000000,695.000000,695.000000,695.000000,695.000000,695.000000,695.000000
mean,23.071160,81.459943,1.289342,2.270047,2.162468,6.748054,1.907286
std,5.718115,6.409021,0.546499,0.464087,0.432503,0.578600,0.285806
min,7.120539,69.383108,0.000000,1.000000,0.000000,0.000000,0.619500
25%,19.894745,76.646578,1.004050,1.959900,1.922550,6.605600,1.734433
50%,24.178088,79.646666,1.137800,2.243700,2.110100,6.998600,1.926133
75%,26.775043,85.595743,1.588100,2.690700,2.466050,7.009200,2.110717
max,34.553852,96.835100,2.870100,3.000000,2.996200,8.717800,2.750833

In [98]:
df.to_csv("Dataset_Y.csv", index=False)
print("Soil dataset transformed successfully")

Soil dataset transformed successfully

In [99]:
import pandas as pd
df=pd.read_csv("Dataset_Y.csv")
df

,state,district,crop,latitude,longitude,n,p,k,ph,soil_fertility
0,maharashtra,"ahilya nagar, maharashtra, india",sugarcane,19.094829,74.747979,1.0361,2.6913,2.2111,7.0752,1.979500
1,maharashtra,"akola, maharashtra, india",cotton,20.700216,77.008168,1.0038,2.6580,2.8295,7.0876,2.163767
2,maharashtra,"amravati, maharashtra, india",cotton,20.931982,77.752304,1.0107,1.4771,2.6801,6.7714,1.722633
3,maharashtra,"chhatrapati sambhaji nagar, maharashtra, india",cotton,19.875754,75.339320,1.0198,2.5394,2.7132,7.1904,2.090800
4,maharashtra,"beed, maharashtra 431122, india",cotton,18.990088,75.753132,1.4096,2.0280,2.4846,7.1908,1.974067
...,...,...,...,...,...,...,...,...,...,...
690,jammu and kashmir,udhampur 182101,maize,32.915985,75.141617,2.2599,2.0020,1.8207,7.0000,2.027533
691,ladakh,kargil 194103,barley,34.553852,76.134894,0.0000,1.7143,1.8572,7.2858,1.190500
692,ladakh,leh,barley,34.152586,77.577054,0.0000,2.0609,2.4656,7.0916,1.508833
693,puducherry,"karaikal, puducherry, india",paddy,10.925440,79.838006,1.0000,2.4920,2.0880,6.9560,1.860000
694,puducherry,"puducherry, india",paddy,11.941591,79.808313,1.0000,2.6735,1.9907,7.0764,1.888067